server:
  port: 8888
  servlet:
    path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.hp.pojo